[package]
name = "neo-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "四级配置合并与执行模式解析"

[dependencies]
neo-protocol = { path = "../neo-protocol", version = "0.1.0" }
serde = { workspace = true }
